### ISSUE TITLE
Missing mailto and tel?

### ISSUE THREAD

**Issue by lunaroja** [rjhilgefort/cordova-plugin-queries-schemes#1]
`- error: "This app is not allowed to query for scheme mailto"`
`- error: "This app is not allowed to query for scheme tel"`

```
<string>tel</string>
<string>mailto</string>
```

**Comment by rjhilgefort** [comment]
Quick google supports the ask- I added them and tagged a new version for you `0.1.3`. In the future, feel free to throw me a PR.
