### ISSUE TITLE
can't uninstall

### ISSUE THREAD

**Issue by busing** [rjhilgefort/cordova-plugin-queries-schemes#2]
can't uninstall

![d32ccc1e-0821-4ee8-ad2a-ceaf9e649bc5](https://cloud.githubusercontent.com/assets/9995678/13978825/eeb575ea-f10e-11e5-8f05-79a5ee970c5c.png)
![d32ccc1e-0821-4ee8-ad2a-ceaf9e649bc5](https://cloud.githubusercontent.com/assets/9995678/13978825/eeb575ea-f10e-11e5-8f05-79a5ee970c5c.png)

**Comment by busing** [comment]
it works after

**Comment by busing** [comment]
it works after 
ionic platform rm ios

**Comment by rjhilgefort** [comment]
Likely an issue with `ionic`\- which I don't have experience with. Let me know if you can provide more information that would indicate something needs to change with this repo.
