### ISSUE TITLE
add own query scheme

### ISSUE THREAD

**Issue by ankurkapil8** [rjhilgefort/cordova-plugin-queries-schemes#6]
Hi,

Can you please add "wooqer" scheme is this plugin. Because every time when I uninstall and install this plugin, I need to add this scheme in plugin.xml.

**Comment by rjhilgefort** [comment]
@ankurkapil8 Sure, but PRs are also welcome and adding entries to the list is extremely easy. See #7 for the changes you requested. Version `0.1.6` is published.
